[phases.setup]
nixPkgs = ["php", "nodejs_20", "phpPackages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]